server:
  port: 18010
#  context-path: /client1

systemName: son-system

spring.h2.console:
  enabled: true
  path: /h2-console
  
logging.level:
  root: warn
  org.springframework:
    boot: info
  com.acompany.asystem: debug